### ISSUE TITLE
As a user, I want to be able to upload a new bathroom location to the application, so that others can be notified of this bathroom. 

### ISSUE THREAD

**Issue by nicholasruan** [nyu-software-engineering/toilet-finder#2]
- [x] User's location setting must allow Toilet Finder to use location
- [x] User's location is captured and saved
- [x] User is shown a map to choose location of new bathroom
- [x] User can input a description to go with the new bathroom upload
- [x] User can choose a tag to go with the bathroom upload
- [x] User can hit Upload to upload new bathroom location to application database

Estimate of work:
Justin and Nick will probably be putting in more effort and work into this user story since they will have to integrate an API that we are learning during this sprint by the end of this sprint. Esther and YK are already a bit familiar with databases and creating database queries so they may finish their portion of this user story before Justin and Nick will. (Refer to Issue #35 for more work Esther and YK will put in to balance this out should this be the case.)

Sprint 2 estimate of work: Mostly tasks on Esther and YK's end that need to be finished so those they will probably put more effort into this one. Nick and Justin should continue working with Google Maps API and React Native to make sure that user location is stored and then made into a comparable data type.

**Comment by esthersun98** [comment]
App function redefined during Sprint 2.
"User can input an image to go with the new bathroom upload"
"User's location and location of new bathroom is checked for proximity for verification"
removed as acceptance criteria for this user story since all toilet location uploads will be the user's location--proximity doesn't need to be checked anymore. We also decided not to have image uploads to save database storage space.
